/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package teatros;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Admin
 */
public class AdminTeatro extends javax.swing.JFrame {

    /**
     * Creates new form AdminTeatro
     */
    public AdminTeatro() {
        initComponents();
        TeatroLabel.setText(Teatros.Teatro);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        IncAgente = new javax.swing.JButton();
        AdminProdu = new javax.swing.JButton();
        IncProdu = new javax.swing.JButton();
        Cerrar = new javax.swing.JButton();
        TeatroLabel = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel.setBackground(new java.awt.Color(102, 0, 0));
        Panel.setMinimumSize(new java.awt.Dimension(900, 720));
        Panel.setOpaque(false);
        Panel.setPreferredSize(new java.awt.Dimension(650, 720));
        Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Administrar");
        Panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 650, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Administrar");
        Panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 650, 70));

        IncAgente.setBackground(new java.awt.Color(51, 51, 51));
        IncAgente.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        IncAgente.setForeground(new java.awt.Color(255, 255, 255));
        IncAgente.setText("Incluir Agente");
        IncAgente.setToolTipText("Incluir un nuevo agente para el teatro");
        IncAgente.setFocusPainted(false);
        IncAgente.setPreferredSize(new java.awt.Dimension(280, 93));
        IncAgente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IncAgenteActionPerformed(evt);
            }
        });
        Panel.add(IncAgente, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 520, 390, 140));

        AdminProdu.setBackground(new java.awt.Color(51, 51, 51));
        AdminProdu.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        AdminProdu.setForeground(new java.awt.Color(255, 255, 255));
        AdminProdu.setText("Administrar Producción");
        AdminProdu.setToolTipText("Incluir un nuevo teatro");
        AdminProdu.setFocusPainted(false);
        AdminProdu.setPreferredSize(new java.awt.Dimension(280, 93));
        AdminProdu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminProduActionPerformed(evt);
            }
        });
        Panel.add(AdminProdu, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 390, 140));

        IncProdu.setBackground(new java.awt.Color(51, 51, 51));
        IncProdu.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        IncProdu.setForeground(new java.awt.Color(255, 255, 255));
        IncProdu.setText("Agregar Producción");
        IncProdu.setToolTipText("Agregar una nueva producción para el teatro");
        IncProdu.setFocusPainted(false);
        IncProdu.setPreferredSize(new java.awt.Dimension(280, 93));
        IncProdu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IncProduActionPerformed(evt);
            }
        });
        Panel.add(IncProdu, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 390, 140));

        Cerrar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Cerrar.setText("Cerrar Sesión");
        Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarActionPerformed(evt);
            }
        });
        Panel.add(Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 690, -1, -1));

        TeatroLabel.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        TeatroLabel.setForeground(new java.awt.Color(255, 255, 255));
        TeatroLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TeatroLabel.setText("<Teatro>");
        Panel.add(TeatroLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 650, -1));

        getContentPane().add(Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FondoAdminSis.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarActionPerformed
        try {
            Teatros.con.close();
        } catch (SQLException ex) {
            Logger.getLogger(AdminTeatro.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
        new LoginFrame();
    }//GEN-LAST:event_CerrarActionPerformed

    private void IncAgenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IncAgenteActionPerformed
        new IncluirAgente(this);
        this.setVisible(false);
    }//GEN-LAST:event_IncAgenteActionPerformed

    private void IncProduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IncProduActionPerformed
        new IncluirProdu(this);
        this.setVisible(false);
    }//GEN-LAST:event_IncProduActionPerformed

    private void AdminProduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminProduActionPerformed
        new AdminProdu(this);
        this.setVisible(false);
    }//GEN-LAST:event_AdminProduActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminTeatro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminTeatro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminTeatro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminTeatro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminTeatro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminProdu;
    private javax.swing.JButton Cerrar;
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton IncAgente;
    private javax.swing.JButton IncProdu;
    private javax.swing.JPanel Panel;
    private javax.swing.JLabel TeatroLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
