/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package teatros;

import java.net.InetAddress;
import java.net.UnknownHostException;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class Agente extends javax.swing.JFrame {

    /**
     * Creates new form Agente
     */
    public Agente() {
        initComponents();
        TeatroLabel.setText(Teatros.Teatro);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        TeatroLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        IncAdminB = new javax.swing.JButton();
        Cerrar = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel.setBackground(new java.awt.Color(102, 0, 0));
        Panel.setMinimumSize(new java.awt.Dimension(900, 720));
        Panel.setOpaque(false);
        Panel.setPreferredSize(new java.awt.Dimension(650, 720));
        Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TeatroLabel.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        TeatroLabel.setForeground(new java.awt.Color(255, 255, 255));
        TeatroLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TeatroLabel.setText("<Teatro>");
        Panel.add(TeatroLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 650, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Agente");
        Panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 650, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Agente");
        Panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 650, 70));

        IncAdminB.setBackground(new java.awt.Color(0, 153, 0));
        IncAdminB.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        IncAdminB.setForeground(new java.awt.Color(255, 255, 255));
        IncAdminB.setText("Vender ticketes");
        IncAdminB.setToolTipText("Incluir un nuevo administrador para un teatro");
        IncAdminB.setFocusPainted(false);
        IncAdminB.setPreferredSize(new java.awt.Dimension(280, 93));
        IncAdminB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IncAdminBActionPerformed(evt);
            }
        });
        Panel.add(IncAdminB, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 390, 140));

        Cerrar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Cerrar.setText("Cerrar Sesión");
        Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarActionPerformed(evt);
            }
        });
        Panel.add(Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 690, -1, -1));

        getContentPane().add(Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FondoAdminSis.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarActionPerformed
        this.dispose();
        new LoginFrame();
    }//GEN-LAST:event_CerrarActionPerformed

    private void IncAdminBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IncAdminBActionPerformed
        new Cartelera();
    }//GEN-LAST:event_IncAdminBActionPerformed

     public static void VerCartelera(Date Ini, Date Fin, DefaultTableModel Tabla)throws SQLException{
            try{
                PreparedStatement ct = Teatros.con.prepareStatement("EXEC SPSobras ?, ?");
                ct.setDate(1, Ini);
                ct.setDate(2, Fin);
                ResultSet rs = ct.executeQuery();
                Tabla.setRowCount(0);
                while(rs.next()){
                    if("confidencial".equals(rs.getString(3))) {
                    } else{
                    Tabla.addRow(new Object[]{rs.getString(1), rs.getString(2)});
                    }

                }
            }catch(SQLException e){
                System.out.println(e.getMessage());
            }    
        }
        
        public static void VerPresentaciones(String ObraNombre, String Teatro, DefaultTableModel Tabla)throws SQLException{
            try{
                PreparedStatement ct = Teatros.con.prepareStatement("EXEC SPSpresentacion ?, ?");
                ct.setString(1, ObraNombre);
                ct.setString(2, Teatro);
                ResultSet rs = ct.executeQuery();
                while(rs.next()){
                    Tabla.addRow(new Object[]{rs.getString(1) + "    -    " + rs.getString(2), rs.getString(3), rs.getString(4)});

                }
            }catch(SQLException e){
                System.out.println(e.getMessage());
            }    
        }
        
            
        public static void CargaFilas(String Teatro, String Bloque, String obra, DefaultTableModel Tabla){
            try{
                PreparedStatement ct = Teatros.con.prepareStatement("EXEC SPSfilas ?, ?");
                ct.setString(1, Teatro);
                ct.setString(2, Bloque);
                ResultSet rs = ct.executeQuery();
                while(rs.next()){
                    String FechaHora = Bloques.TablaBloques.getValueAt(Bloques.TablaBloques.getSelectedRow(), 0).toString();
                    String fecha = FechaHora.split("    -    ")[0];
                    String hora = FechaHora.split("    -    ")[1];
                    Tabla.addRow(new Object[]{rs.getString(1), Integer.parseInt(rs.getString(2))-CuentaAsiento(Teatro, obra, Bloque, rs.getString(1), fecha, hora)});

                }
            }catch(SQLException e){
                System.out.println(e.getMessage());
            }   
        }
        
        public static void CreaRegistroCompra(int aleatorio, int cantidad, String Titulo) throws UnknownHostException{
            InetAddress address = InetAddress.getLocalHost();
            try{
                PreparedStatement ct = Teatros.con.prepareStatement("EXEC SPIregistro ?, ?, ?, ?");
                ct.setString(1, address.getHostAddress());
                ct.setInt(2, aleatorio);
                ct.setInt(3, cantidad);
                ct.setString(4, Titulo);
                ct.executeUpdate();
            }catch(SQLException e){
                System.out.println(e.getMessage());
            }
        
        }
        
        public static String BuscaAsiento(String teatro, String produ, String bloque, String fila, String fecha, String Hora, int numasiento){
            boolean found = false;
            String usados = "Los asientos ya usados son: ";
            try{
                PreparedStatement ct = Teatros.con.prepareStatement("EXEC SPSasientos ?, ?, ?, ?, ?, ?, ?");
                ct.setString(1, teatro);
                ct.setString(2, produ);
                ct.setString(3, bloque);
                ct.setString(4, fila);
                ct.setString(5, fecha);
                ct.setString(6, Hora);
                ct.setInt(7, numasiento);
                ResultSet rs = ct.executeQuery();
                if(rs.next()){
                    usados = usados + rs.getInt(1);
                    while(rs.next()){
                        System.out.println(rs.getInt(1));
                        usados = usados + " - " + rs.getInt(1);

                    }
                }
                else{
                    return "";
                }
                return usados;
            }catch(SQLException e){
                System.out.println(e.getMessage());
            }
        return "";
        }
        
        public static void InsertarAsientos(String teatro, String produ, String bloque, String fila, String fecha, String hora, int numasiento, String IP, int cantidad, int numreg, int monto){
        try{
                PreparedStatement ct = Teatros.con.prepareStatement("EXEC SPIasientos ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?");
                ct.setString(1, teatro);
                ct.setString(2, produ);
                ct.setString(3, bloque);
                ct.setString(4, fila);
                ct.setString(5, fecha);
                ct.setString(6, hora);
                ct.setInt(7, numasiento);
                ct.setString(8, IP);
                ct.setInt(9, cantidad);
                ct.setInt(10, numreg);
                ct.setInt(11, monto);
                ct.executeUpdate();

            }catch(SQLException e){
                System.out.println(e.getMessage());
            }
        }
        
        public static int CuentaAsiento(String teatro, String produ, String bloque, String fila, String fecha, String Hora) throws SQLException{
            try{
                PreparedStatement ct = Teatros.con.prepareStatement("EXEC SPCasientos ?, ?, ?, ?, ?, ?");
                ct.setString(1, teatro);
                ct.setString(2, produ);
                ct.setString(3, bloque);
                ct.setString(4, fila);
                ct.setString(5, fecha);
                ct.setString(6, Hora);
                ResultSet rs = ct.executeQuery();
                rs.next();
                return rs.getInt(1);
                }
            catch(SQLException e){
                System.out.println(e.getMessage());
            }
            return 0;
        }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cerrar;
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton IncAdminB;
    private javax.swing.JPanel Panel;
    private javax.swing.JLabel TeatroLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
