/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package teatros;

import static com.sun.xml.internal.fastinfoset.alphabet.BuiltInRestrictedAlphabets.table;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.table.DefaultTableModel;




/**
 *
 * @author Admin
 */
public class IncluirTeatro extends javax.swing.JFrame {
    JFrame principal;
    DefaultTableModel modelo, modelo2;
    public WindowListener c = new WindowAdapter() {
        @Override
        public void windowClosing(WindowEvent e) {
            cerrar();
        }
    };
    
    ArrayList<String> bloques = new ArrayList<>();
    ArrayList<Integer> cantFilas = new ArrayList<>();
    ArrayList<Integer[]> asientosXFila = new ArrayList<>();
    ArrayList<String[]> datos = new ArrayList<>();
    int cantAsientos = 0;
    
    
    /**
     * Creates new form IncluirTeatro
     * @param p
     */
    public IncluirTeatro(JFrame p) {
        initComponents();
        principal = p;
        modelo = (DefaultTableModel) TablaBloques.getModel();
        modelo2 = (DefaultTableModel) tablaFilas.getModel();
        PanelAsientos.setVisible(false);
        PanelFilas.setVisible(false);
        this.addWindowListener(c);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }
    
    void cerrar(){
        this.dispose();
        principal.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        PanelFilas = new javax.swing.JPanel();
        Guardar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaFilas = new javax.swing.JTable();
        PanelAsientos = new javax.swing.JPanel();
        BSiguiente2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tBloque = new javax.swing.JTextField();
        AgregarBloque = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        ComboBloques = new javax.swing.JComboBox<>();
        sFilas = new javax.swing.JSpinner();
        AgregarFila = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaBloques = new javax.swing.JTable();
        PanelDatos = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BSiguiente = new javax.swing.JButton();
        tNombre = new javax.swing.JTextField();
        tDireccion = new javax.swing.JTextField();
        tTelefono = new javax.swing.JTextField();
        tCorreo = new javax.swing.JTextField();
        tWeb = new javax.swing.JTextField();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Insertar Teatro");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Agregar Teatro");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 700, -1));

        PanelFilas.setBackground(new java.awt.Color(0, 102, 153));
        PanelFilas.setOpaque(false);
        PanelFilas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Guardar.setBackground(new java.awt.Color(51, 51, 51));
        Guardar.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        Guardar.setForeground(new java.awt.Color(255, 255, 255));
        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        PanelFilas.add(Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, -1, -1));

        tablaFilas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bloque", "Fila", "Asientos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaFilas.setRequestFocusEnabled(false);
        tablaFilas.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tablaFilas);
        if (tablaFilas.getColumnModel().getColumnCount() > 0) {
            tablaFilas.getColumnModel().getColumn(0).setResizable(false);
            tablaFilas.getColumnModel().getColumn(1).setResizable(false);
            tablaFilas.getColumnModel().getColumn(2).setResizable(false);
            tablaFilas.getColumnModel().getColumn(2).setCellEditor(null);
        }

        PanelFilas.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        getContentPane().add(PanelFilas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 700, 600));

        PanelAsientos.setBackground(new java.awt.Color(0, 102, 51));
        PanelAsientos.setOpaque(false);
        PanelAsientos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BSiguiente2.setBackground(new java.awt.Color(51, 51, 51));
        BSiguiente2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        BSiguiente2.setForeground(new java.awt.Color(255, 255, 255));
        BSiguiente2.setText("Siguiente");
        BSiguiente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSiguiente2ActionPerformed(evt);
            }
        });
        PanelAsientos.add(BSiguiente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 480, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Filas :");
        PanelAsientos.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 170, 30));

        tBloque.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tBloque.setForeground(new java.awt.Color(0, 0, 0));
        PanelAsientos.add(tBloque, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 72, 420, -1));

        AgregarBloque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonMas.png"))); // NOI18N
        AgregarBloque.setBorderPainted(false);
        AgregarBloque.setFocusPainted(false);
        AgregarBloque.setPreferredSize(new java.awt.Dimension(37, 37));
        AgregarBloque.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonMasP.png"))); // NOI18N
        AgregarBloque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarBloqueActionPerformed(evt);
            }
        });
        PanelAsientos.add(AgregarBloque, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Bloque :");
        PanelAsientos.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 170, 30));

        ComboBloques.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        ComboBloques.setForeground(new java.awt.Color(0, 0, 0));
        ComboBloques.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboBloquesItemStateChanged(evt);
            }
        });
        PanelAsientos.add(ComboBloques, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 330, 40));

        sFilas.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        sFilas.setModel(new javax.swing.SpinnerNumberModel(1, 1, 26, 1));
        sFilas.setOpaque(false);
        PanelAsientos.add(sFilas, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 70, 40));

        AgregarFila.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonMas.png"))); // NOI18N
        AgregarFila.setBorderPainted(false);
        AgregarFila.setFocusPainted(false);
        AgregarFila.setPreferredSize(new java.awt.Dimension(37, 37));
        AgregarFila.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BotonMasP.png"))); // NOI18N
        AgregarFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarFilaActionPerformed(evt);
            }
        });
        PanelAsientos.add(AgregarFila, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, -1, -1));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        TablaBloques.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bloque", "Filas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaBloques.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TablaBloques);
        if (TablaBloques.getColumnModel().getColumnCount() > 0) {
            TablaBloques.getColumnModel().getColumn(0).setResizable(false);
            TablaBloques.getColumnModel().getColumn(1).setResizable(false);
        }

        PanelAsientos.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 430, 250));

        getContentPane().add(PanelAsientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 700, 600));

        PanelDatos.setBackground(new java.awt.Color(0, 102, 102));
        PanelDatos.setOpaque(false);
        PanelDatos.setPreferredSize(new java.awt.Dimension(700, 600));
        PanelDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Nombre :");
        PanelDatos.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 200, 40));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Dirección :");
        PanelDatos.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 200, 40));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Teléfono :");
        PanelDatos.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 200, 40));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Correo :");
        PanelDatos.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 200, 40));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Sitio web :");
        PanelDatos.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 200, 40));

        BSiguiente.setBackground(new java.awt.Color(51, 51, 51));
        BSiguiente.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        BSiguiente.setForeground(new java.awt.Color(255, 255, 255));
        BSiguiente.setText("Siguiente");
        BSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSiguienteActionPerformed(evt);
            }
        });
        PanelDatos.add(BSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 480, -1, -1));

        tNombre.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        PanelDatos.add(tNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 420, 40));

        tDireccion.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        PanelDatos.add(tDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 420, 40));

        tTelefono.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        PanelDatos.add(tTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 130, 40));

        tCorreo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        PanelDatos.add(tCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 420, 40));

        tWeb.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        PanelDatos.add(tWeb, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 420, 40));

        getContentPane().add(PanelDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FondoIncTeatro.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSiguienteActionPerformed
        String nombre, direccion, telefono, correo, web;
        
        nombre = tNombre.getText();
        direccion = tDireccion.getText();
        telefono = tTelefono.getText();
        correo = tCorreo.getText();
        web = tWeb.getText();
        
        if(revisarDatos(nombre, direccion, telefono, correo, web)){
            
            if(Teatros.revisaTeatro(this, nombre, direccion, Integer.parseInt(telefono), correo, web)){
                PanelDatos.setVisible(false);
                PanelAsientos.setVisible(true);
            }
            
        }
        
    }//GEN-LAST:event_BSiguienteActionPerformed

    
    boolean revisarDatos(String nombre, String direccion, String telefono, String correo, String web){
        if(nombre.trim().isEmpty() || direccion.trim().isEmpty() || telefono.trim().isEmpty() || correo.trim().isEmpty() || web.trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Debe llenar todos los datos", "Advertencia", 0);
        
        }else if(!(telefono.length() == 8 && Teatros.isNumeric(telefono))){
            JOptionPane.showMessageDialog(this, "Teléfono inválido", "Advertencia",0);
            
        }else{
            return true;
        }
            
        return false;
    }
    
    
    private void BSiguiente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSiguiente2ActionPerformed
        
        if(TablaBloques.getRowCount() == 0)
            return;
        
        for(Integer cant : cantFilas){
            asientosXFila.add(new Integer[cant]);
        }
        
        for(int i = 0; i < bloques.size(); i++){
            for(int j = 0; j < cantFilas.get(i); j++){
                modelo2.addRow(new Object[]{bloques.get(i), (char)(j+'A'), 0});
            }
        }
        
        
        PanelAsientos.setVisible(false);
        PanelFilas.setVisible(true);
    }//GEN-LAST:event_BSiguiente2ActionPerformed

    private void AgregarBloqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarBloqueActionPerformed
        String bloque = tBloque.getText();
        
        if(!(bloque.trim().isEmpty() || bloques.contains(bloque))){
            tBloque.setText("");
            
            bloques.add(bloque);
            cantFilas.add(1);
            
            modelo.addRow(new Object[]{bloque, 1});
            ComboBloques.addItem(bloque);
        }
    }//GEN-LAST:event_AgregarBloqueActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        String bloqueAnt = tablaFilas.getValueAt(0, 0).toString();
        String fila;
        
        int asientos = 0;
        for(int i = 0, j = 0, k = 0; i < tablaFilas.getRowCount(); i++){
            
            fila = tablaFilas.getValueAt(i, 1).toString();
            asientos = (int)tablaFilas.getValueAt(i, 2);
            
            datos.add(new String[]{bloqueAnt, fila, Integer.toString(asientos)});
            
            cantAsientos += asientos;
            
            
            k++;
            try{
                if(bloqueAnt != tablaFilas.getValueAt(i+1, 0)){
                    j++;
                    k=0;
                    bloqueAnt = tablaFilas.getValueAt(i+1, 0).toString();
                }
            }catch(Exception e){
                break;
            }
        }
        
        
        
    }//GEN-LAST:event_GuardarActionPerformed

    private void AgregarFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarFilaActionPerformed
        int indice = ComboBloques.getSelectedIndex();
        int valor = (int) sFilas.getValue();
        cantFilas.set(indice, valor);
        modelo.setValueAt(valor, indice, 1);
    }//GEN-LAST:event_AgregarFilaActionPerformed

    private void ComboBloquesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboBloquesItemStateChanged
        int indice = ComboBloques.getSelectedIndex();
        sFilas.setValue(cantFilas.get(indice));
    }//GEN-LAST:event_ComboBloquesItemStateChanged

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IncluirTeatro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IncluirTeatro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IncluirTeatro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IncluirTeatro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IncluirTeatro(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarBloque;
    private javax.swing.JButton AgregarFila;
    private javax.swing.JButton BSiguiente;
    private javax.swing.JButton BSiguiente2;
    private javax.swing.JComboBox<String> ComboBloques;
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton Guardar;
    private javax.swing.JPanel PanelAsientos;
    private javax.swing.JPanel PanelDatos;
    private javax.swing.JPanel PanelFilas;
    private javax.swing.JTable TablaBloques;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner sFilas;
    private javax.swing.JTextField tBloque;
    private javax.swing.JTextField tCorreo;
    private javax.swing.JTextField tDireccion;
    private javax.swing.JTextField tNombre;
    private javax.swing.JTextField tTelefono;
    private javax.swing.JTextField tWeb;
    private javax.swing.JTable tablaFilas;
    // End of variables declaration//GEN-END:variables
}
