/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package teatros;

/**
 *
 * @author Admin
 */
public class Principal extends javax.swing.JFrame {
    public static String User, Password, Tipo;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        
        User = Teatros.User;
        Password = Teatros.Password;
        Tipo = Teatros.Tipo;
        
        habilitarOpciones();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }
    
    void habilitarOpciones(){
        if("AdminSis".equals(Tipo)){
            AdminProdB.setEnabled(true);
            DefinirProdB.setEnabled(true);
            IncAdminB.setEnabled(true);
            IncAgenteB.setEnabled(true);
            IncTeatroB.setEnabled(true);
            
        }else if("AdminTeatro".equals(Tipo)){
            AdminProdB.setEnabled(true);
            DefinirProdB.setEnabled(true);
            IncAdminB.setEnabled(true);
            IncAgenteB.setEnabled(true);
            IncTeatroB.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        VenderB = new javax.swing.JButton();
        DefinirProdB = new javax.swing.JButton();
        AdminProdB = new javax.swing.JButton();
        IncAgenteB = new javax.swing.JButton();
        IncTeatroB = new javax.swing.JButton();
        IncAdminB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrador de Teatros");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(900, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Administrar Teatro");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 40, 920, -1));

        VenderB.setBackground(new java.awt.Color(0, 204, 0));
        VenderB.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        VenderB.setText("Vender Ticketes");
        VenderB.setToolTipText("Vender ticketes a un cliente");
        VenderB.setPreferredSize(new java.awt.Dimension(300, 93));
        jPanel1.add(VenderB, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 410, 110));

        DefinirProdB.setFont(new java.awt.Font("Dialog", 1, 28)); // NOI18N
        DefinirProdB.setText("Definir Producción");
        DefinirProdB.setToolTipText("No tienes permiso para usar esta función");
        DefinirProdB.setEnabled(false);
        DefinirProdB.setFocusPainted(false);
        DefinirProdB.setPreferredSize(new java.awt.Dimension(300, 93));
        jPanel1.add(DefinirProdB, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 343, -1, 110));

        AdminProdB.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        AdminProdB.setText("Administrar Producciones");
        AdminProdB.setToolTipText("No tienes permiso para usar esta función");
        AdminProdB.setEnabled(false);
        AdminProdB.setFocusPainted(false);
        AdminProdB.setPreferredSize(new java.awt.Dimension(300, 93));
        jPanel1.add(AdminProdB, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 343, -1, 110));

        IncAgenteB.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        IncAgenteB.setText("Incluir Agente");
        IncAgenteB.setToolTipText("No tienes permiso para usar esta función");
        IncAgenteB.setEnabled(false);
        IncAgenteB.setFocusPainted(false);
        IncAgenteB.setPreferredSize(new java.awt.Dimension(280, 93));
        jPanel1.add(IncAgenteB, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 523, -1, 110));

        IncTeatroB.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        IncTeatroB.setText("Incluir Teatro");
        IncTeatroB.setToolTipText("No tienes permiso para usar esta función");
        IncTeatroB.setEnabled(false);
        IncTeatroB.setFocusPainted(false);
        IncTeatroB.setPreferredSize(new java.awt.Dimension(280, 93));
        jPanel1.add(IncTeatroB, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 523, -1, 110));

        IncAdminB.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        IncAdminB.setText("Incluir Administrador");
        IncAdminB.setToolTipText("No tienes permiso para usar esta función");
        IncAdminB.setEnabled(false);
        IncAdminB.setFocusPainted(false);
        IncAdminB.setPreferredSize(new java.awt.Dimension(280, 93));
        jPanel1.add(IncAdminB, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 523, -1, 110));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminProdB;
    private javax.swing.JButton DefinirProdB;
    private javax.swing.JButton IncAdminB;
    private javax.swing.JButton IncAgenteB;
    private javax.swing.JButton IncTeatroB;
    private javax.swing.JButton VenderB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
